// lib/mockData.ts
import { Alumni, Event, NewsItem, Job } from '@/types';

export const mockAlumni: Alumni[] = [
  {
    id: '1',
    fullName: 'Sarah Jenkins',
    email: 'sarah.j@alumni.edu',
    department: 'Computer Science',
    graduationYear: '2014',
    currentCompany: 'Google',
    currentRole: 'Senior Product Manager',
    location: 'San Francisco Bay Area',
    profilePicture: 'https://randomuser.me/api/portraits/women/44.jpg',
    linkedin: 'https://linkedin.com/in/sarahjenkins',
    website: 'https://sarahjenkins.io',
    skills: ['Product Management', 'Agile Methodology', 'User Research', 'Data Analytics', 'Leadership'],
    bio: 'Passionate product leader with over 9 years of experience in building scalable tech products. Currently leading the Maps initialization team at Google. Dedicated to mentoring the next generation of product managers.',
    isOnline: true,
    experience: [
      { id: 'e1', company: 'Google', role: 'Senior Product Manager', location: 'San Francisco, CA', startYear: '2019', endYear: 'Present' },
      { id: 'e2', company: 'Meta', role: 'Product Manager', location: 'Menlo Park, CA', startYear: '2016', endYear: '2019' },
      { id: 'e3', company: 'Startup XYZ', role: 'Associate PM', location: 'San Francisco, CA', startYear: '2014', endYear: '2016' },
    ],
    education: [
      { id: 'ed1', institution: 'University', degree: 'Bachelor of Science', field: 'Computer Science', startYear: '2010', endYear: '2014', activities: 'Student Government, Coding Club President' },
    ],
  },
  {
    id: '2',
    fullName: 'Marcus Thorne',
    email: 'marcus.t@alumni.edu',
    department: 'MBA',
    graduationYear: '2020',
    currentCompany: 'Goldman Sachs',
    currentRole: 'Investment Associate',
    location: 'New York, NY',
    profilePicture: 'https://randomuser.me/api/portraits/men/32.jpg',
    linkedin: 'https://linkedin.com/in/marcusthorne',
    skills: ['Financial Modeling', 'Investment Analysis', 'Risk Management', 'Python', 'Excel'],
    bio: 'Finance professional specializing in equity research and investment banking. Passionate about connecting alumni with financial opportunities.',
    experience: [
      { id: 'e1', company: 'Goldman Sachs', role: 'Investment Associate', location: 'New York, NY', startYear: '2020', endYear: 'Present' },
      { id: 'e2', company: 'JP Morgan', role: 'Analyst Intern', location: 'New York, NY', startYear: '2019', endYear: '2020' },
    ],
    education: [
      { id: 'ed1', institution: 'University', degree: 'Master of Business Administration', field: 'Finance', startYear: '2018', endYear: '2020' },
    ],
  },
  {
    id: '3',
    fullName: 'Elena Rodriguez',
    email: 'elena.r@alumni.edu',
    department: 'Economics',
    graduationYear: '2022',
    currentCompany: 'Spotify',
    currentRole: 'Data Analyst',
    location: 'Stockholm, Sweden',
    profilePicture: 'https://randomuser.me/api/portraits/women/68.jpg',
    linkedin: 'https://linkedin.com/in/elenarodriguez',
    skills: ['Python', 'SQL', 'Tableau', 'Machine Learning', 'Statistics'],
    bio: 'Data-driven economist turning raw data into actionable insights at Spotify. Love music, numbers, and making data accessible.',
    isOnline: true,
    experience: [
      { id: 'e1', company: 'Spotify', role: 'Data Analyst', location: 'Stockholm, Sweden', startYear: '2022', endYear: 'Present' },
    ],
    education: [
      { id: 'ed1', institution: 'University', degree: 'Bachelor of Arts', field: 'Economics', startYear: '2018', endYear: '2022' },
    ],
  },
  {
    id: '4',
    fullName: 'David Chen',
    email: 'david.c@alumni.edu',
    department: 'Law',
    graduationYear: '2015',
    currentCompany: 'Netflix',
    currentRole: 'Senior Counsel',
    location: 'Los Angeles, CA',
    profilePicture: 'https://randomuser.me/api/portraits/men/52.jpg',
    linkedin: 'https://linkedin.com/in/davidchen',
    skills: ['Corporate Law', 'IP Law', 'Contract Negotiation', 'Compliance', 'Entertainment Law'],
    bio: 'Entertainment and technology lawyer at Netflix, navigating complex IP landscapes in the streaming era.',
    experience: [
      { id: 'e1', company: 'Netflix', role: 'Senior Counsel', location: 'Los Angeles, CA', startYear: '2018', endYear: 'Present' },
      { id: 'e2', company: 'Warner Bros', role: 'Associate Attorney', location: 'Burbank, CA', startYear: '2015', endYear: '2018' },
    ],
    education: [
      { id: 'ed1', institution: 'University', degree: 'Juris Doctor', field: 'Law', startYear: '2012', endYear: '2015' },
    ],
  },
  {
    id: '5',
    fullName: 'Priya Nair',
    email: 'priya.n@alumni.edu',
    department: 'Electrical Engineering',
    graduationYear: '2017',
    currentCompany: 'Tesla',
    currentRole: 'Senior Hardware Engineer',
    location: 'Austin, TX',
    profilePicture: 'https://randomuser.me/api/portraits/women/26.jpg',
    skills: ['PCB Design', 'Embedded Systems', 'C++', 'Python', 'FPGA'],
    bio: 'Hardware engineer working on next-generation EV battery management systems at Tesla. Passionate about sustainable technology.',
    experience: [
      { id: 'e1', company: 'Tesla', role: 'Senior Hardware Engineer', location: 'Austin, TX', startYear: '2020', endYear: 'Present' },
      { id: 'e2', company: 'Intel', role: 'Hardware Engineer', location: 'Santa Clara, CA', startYear: '2017', endYear: '2020' },
    ],
    education: [
      { id: 'ed1', institution: 'University', degree: 'Bachelor of Engineering', field: 'Electrical Engineering', startYear: '2013', endYear: '2017' },
    ],
  },
  {
    id: '6',
    fullName: 'James Okafor',
    email: 'james.o@alumni.edu',
    department: 'Computer Science',
    graduationYear: '2019',
    currentCompany: 'Microsoft',
    currentRole: 'Software Engineer II',
    location: 'Seattle, WA',
    profilePicture: 'https://randomuser.me/api/portraits/men/61.jpg',
    linkedin: 'https://linkedin.com/in/jamesokafor',
    skills: ['TypeScript', 'React', 'Azure', 'Node.js', 'System Design'],
    bio: 'Full-stack engineer at Microsoft working on Azure DevOps. Open source contributor and tech community builder.',
    isOnline: true,
    experience: [
      { id: 'e1', company: 'Microsoft', role: 'Software Engineer II', location: 'Seattle, WA', startYear: '2021', endYear: 'Present' },
      { id: 'e2', company: 'Amazon', role: 'SDE I', location: 'Seattle, WA', startYear: '2019', endYear: '2021' },
    ],
    education: [
      { id: 'ed1', institution: 'University', degree: 'Bachelor of Science', field: 'Computer Science', startYear: '2015', endYear: '2019' },
    ],
  },
  {
    id: '7',
    fullName: 'Aisha Patel',
    email: 'aisha.p@alumni.edu',
    department: 'Biomedical Engineering',
    graduationYear: '2016',
    currentCompany: 'Johnson & Johnson',
    currentRole: 'R&D Manager',
    location: 'New Brunswick, NJ',
    profilePicture: 'https://randomuser.me/api/portraits/women/55.jpg',
    skills: ['Medical Devices', 'R&D', 'Regulatory Affairs', 'MATLAB', 'Project Management'],
    bio: 'Leading R&D initiatives in medical device innovation. Passionate about bringing healthcare technology to patients worldwide.',
    experience: [
      { id: 'e1', company: 'Johnson & Johnson', role: 'R&D Manager', location: 'New Brunswick, NJ', startYear: '2020', endYear: 'Present' },
    ],
    education: [
      { id: 'ed1', institution: 'University', degree: 'Bachelor of Engineering', field: 'Biomedical Engineering', startYear: '2012', endYear: '2016' },
    ],
  },
  {
    id: '8',
    fullName: 'Ryan Thompson',
    email: 'ryan.t@alumni.edu',
    department: 'Marketing',
    graduationYear: '2021',
    currentCompany: 'Airbnb',
    currentRole: 'Growth Marketing Manager',
    location: 'San Francisco, CA',
    profilePicture: 'https://randomuser.me/api/portraits/men/23.jpg',
    skills: ['Digital Marketing', 'SEO', 'Growth Hacking', 'Analytics', 'Content Strategy'],
    bio: 'Growth marketer driving user acquisition strategies at Airbnb. Former founder of a travel startup.',
    experience: [
      { id: 'e1', company: 'Airbnb', role: 'Growth Marketing Manager', location: 'San Francisco, CA', startYear: '2022', endYear: 'Present' },
      { id: 'e2', company: 'Startup', role: 'Founder', location: 'Remote', startYear: '2021', endYear: '2022' },
    ],
    education: [
      { id: 'ed1', institution: 'University', degree: 'Bachelor of Business', field: 'Marketing', startYear: '2017', endYear: '2021' },
    ],
  },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Class of 2014 Decennial Reunion',
    date: 'October 15, 2023',
    time: '6:00 PM',
    location: 'Great Hall, University Campus',
    type: 'reunion',
    description: 'Celebrate 10 years since graduation with your fellow classmates. Formal dinner, awards ceremony, and campus tours.',
    image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&auto=format&fit=crop',
    attendees: 147,
    isFeatured: true,
    isOnline: false,
  },
  {
    id: '2',
    title: 'Tech Alumni Mixer',
    date: 'October 22, 2023',
    time: '7:00 PM',
    location: 'Innovation Hub, Downtown',
    type: 'networking',
    description: 'Meet fellow alumni in the tech industry. Network, share experiences, and explore collaboration opportunities.',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop',
    attendees: 89,
    isOnline: false,
  },
  {
    id: '3',
    title: 'Future of AI Ethics Webinar',
    date: 'November 5, 2023',
    time: '4:00 PM',
    location: 'Online Event',
    type: 'webinar',
    description: 'Join our panel of AI experts and ethicists for an in-depth discussion on responsible AI development.',
    attendees: 312,
    isOnline: true,
  },
  {
    id: '4',
    title: 'MBA Networking Coffee',
    date: 'November 12, 2023',
    time: '9:00 AM',
    location: 'Campus Bistro',
    type: 'networking',
    description: 'Informal coffee meetup for MBA alumni and current students to connect and share industry insights.',
    attendees: 43,
    isOnline: false,
  },
  {
    id: '5',
    title: '10-Year Engineering Reunion',
    date: 'October 24, 2023',
    time: '5:00 PM',
    location: 'Main Quad, South Campus',
    type: 'reunion',
    description: 'Engineering class reunion with lab tours, demos from current students, and dinner reception.',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
    attendees: 201,
    isFeatured: true,
    isOnline: false,
  },
];

export const mockNews: NewsItem[] = [
  {
    id: '1',
    title: 'Alumni Fund Exceeds $50 Million Milestone',
    excerpt: 'The Annual Giving Campaign has surpassed expectations, with alumni contributions reaching a record-breaking $50 million this fiscal year.',
    content: 'Full content here...',
    date: 'October 8, 2023',
    category: 'Announcement',
    image: 'https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&auto=format&fit=crop',
    author: 'Alumni Relations Office',
  },
  {
    id: '2',
    title: 'Dr. Sarah Jenkins Named Top 40 Under 40',
    excerpt: 'Our distinguished alumna has been recognized among the most influential young professionals shaping the technology industry.',
    content: 'Full content here...',
    date: 'October 3, 2023',
    category: 'Achievement',
    image: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800&auto=format&fit=crop',
    author: 'Communications Team',
  },
  {
    id: '3',
    title: 'New Mentorship Program Launches This Fall',
    excerpt: 'Connect with experienced alumni mentors across industries through our newly redesigned mentorship matching platform.',
    content: 'Full content here...',
    date: 'September 28, 2023',
    category: 'Programs',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop',
    author: 'Career Services',
  },
];

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Product Designer',
    company: 'DesignCo',
    location: 'San Francisco, CA · Hybrid',
    type: 'full-time',
    salary: '$140k - $180k',
    isAlumniOwned: true,
    postedAt: '2h ago',
  },
  {
    id: '2',
    title: 'Software Engineering Intern',
    company: 'GlobalTech Solutions',
    location: 'Remote (Global)',
    type: 'internship',
    duration: '3 Months',
    postedAt: '2h ago',
  },
  {
    id: '3',
    title: 'Marketing Manager',
    company: 'Startup Hub',
    location: 'New York, NY · On-site',
    type: 'full-time',
    referrals: 3,
    postedAt: '5h ago',
  },
  {
    id: '4',
    title: 'Backend Developer',
    company: 'DataSphere',
    location: 'Austin, TX · Hybrid',
    type: 'full-time',
    experience: 'Junior (1-3 yrs)',
    postedAt: '1d ago',
  },
];

export const departments = [
  'All Departments',
  'Computer Science',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Biomedical Engineering',
  'MBA',
  'Economics',
  'Law',
  'Marketing',
  'Mathematics',
  'Physics',
  'Chemistry',
];

export const graduationYears = Array.from({ length: 30 }, (_, i) => String(new Date().getFullYear() - i));

export const locations = [
  'All Locations',
  'San Francisco Bay Area',
  'New York, NY',
  'Seattle, WA',
  'Austin, TX',
  'London, UK',
  'Stockholm, Sweden',
  'Los Angeles, CA',
  'Boston, MA',
  'Chicago, IL',
];

export const companies = [
  'All Companies',
  'Google',
  'Microsoft',
  'Amazon',
  'Meta',
  'Apple',
  'Netflix',
  'Tesla',
  'Goldman Sachs',
  'Spotify',
  'Airbnb',
];

export const featuredAlumni = mockAlumni.slice(0, 3);

export const stats = {
  alumni: '35k+',
  jobs: '1.2k+',
  events: '300+',
  mentors: '500+',
};
